### ISSUE TITLE
Notes_for_Arduino_users

### ISSUE THREAD

**Issue by jc508** [vortex314/serial2mqtt#3]
Notes: for Arduino users of serial2mqtt
The Arduino boards have a 64 byte buffer for (hardware) serial input and output.
The code has to consume or take data from this buffer before it fills as characters received after that are simply lost.

In the sample code in the README.md this means that the `while (Serial.available())` loop has to be entered very regulalry in order to remove the characters from the buffer and append to the line

Given that the format of the messages to and from the gateway tend to be long, in comparison to the 64 byte buffer, typically at least two bufferfulls will be required.
Put another way: an empty message with only half a topic such as :-
 **{"cmd":"MQTT-PUB","message":,"topic":"dst/jcrpi.USB0/"}**
is 55 bytes long. Then any real message will exceed the 64 bytes. So there is no way the gateway can send a message and have it all stored in the buffer until your sketch gets around to reading it.

There are two things here that contribute to this timing issue
1. the high baud rate
2. the delay()  commands

As it stands the sketch can be made to work if the baud rate is reduced from 115200 to 2400.
Or if the delay() is reduced to 10 (.01sec)

People implementing this solution will need to be vitally aware of how long their main loop takes and adjust the baud rate appropriately. (At both ends of the gateway of course) 
JC

**Comment by vortex314** [comment]
Hi JC,

indeed correct observations. As I found the JSON objects very verbose, I switched to Json Array. 
Example : [0,"topic",1.234]
Code under development can be found the 'develop' branch. 
Anyway as no flow control is implemented ( to keep it simple ), you will need to throttle the flow yourself. Or make the reception asynchronously. I guess the PI will not have any issues keeping up with the arduino. Most of the time the arduino will be sending a lot and do little receiving.

It's best to assume that the communication is happening on an unreliable medium. 

Some Arduino versions can change the UART buffer size. 

Lieven

**Comment by jc508** [comment]
Lieven,

Firstly this stuff is not my bread-and-butter and I don’t know the rules and etiquette for interacting on github.

And I haven’t coded in C or C++ for over 20 years and its apparent the world has moved on a lot in that time.

Nevertheless I did clone your work (and its myriad of related modules) to make a couple of hacks that you may consider including in your next release if you are still actively developing.

 

As you may have gathered my current platform is a Raspberry PI with an Arduino as the lower ‘Lizard brain’.

These are connected with a simple usb cable which, at this early developmental stage, powers the Arduino. 

So the 1st issue is the Arduino is up and working pretty much as soon as the power is switched on - way before I get to start anything else

Secondly either the gateway or the Arduino can be pulled off line for tinkering at any time. 

I also wanted the gateway to be ‘message agnostic’ – so I disabled all the auto subscription code.

 

I have observed 2 things.

*	If the serial plug is pulled the gateway has only one try to reconnect.
*	If the gateway is closed and restarted then any subscriptions the lower serial device had are lost

 

For the first issue I have changed

                                WARN(" disconnecting serial no new data received in %d msec",5000);

                                                // a bit rough but hopefully will keep trying until the Arduino is plugged in again

                                while (! _serialConnected ) {

                                                  sleep(5);

                                                  serialConnect();

                                  }

                                }

 

For the 2nd issue (because I have removed the auto subscribe)

I have added a new mandatory message down to the serial device. Its called "serial2mqtt/restarted"

Which is a command to the serial device – hopefully to resubscribe to what it needs

New code is

                                                                case MQTT_CONNECT_SUCCESS : {

                                                                                                INFO("MQTT_CONNECT_SUCCESS %s ",_serialPortShort.c_str());

                                                                                                _mqttConnected=true;

//                                                                                            mqttSubscribe(_mqttSubscribedTo);  // removed JC. this is the blanket auto subscribe

//                          instead force the serial device to re-subscribe to what it needs

                        serialPublish("serial2mqtt/restarted", " ", 0, false);

                                                                                                break;

                                                                                }

 

After these changes it seems to sort its self out if either bit is removed.

 

I apologise if I am overstepping the mark by suggesting changes – I didn’t want to raise an ‘issue’.

 

Thanks

JC

**Comment by vortex314** [comment]
Hi JC,

no reason to apologize, always welcoming feedback on my code and features offered. 
Indeed as I was starting actively to use my own code again, I noticed the bug of connection re-establishment also. I corrected it in a different way, see new version. Feel free to test, it also contains the support of JsonArray instead of JsonObject in the protocol. Configuration driven. 

My use case is similar to yours ,see : https://vortex314.blogspot.com/2019/06/step-2-remote-controller-via-akka.html

The difference is that I use an Arduino-capable device but with an RTOS ( FreeRtos and ESP-IDF on an ESP32 and ESP8266 ) and an Actor framework : Akka ( in my case microAkka ) 

To handle connection loss and re-establishment I've implemented a similar way as your proposal : The arduino is sending an MQTT publish to which it subscribes itself. As long this loopback message is received it means that an end-to-end connection to MQTT broker exists ( not only to serial2mtt ). Until this loopback MQTT publish is received the Arduino keeps on sending a subscribe and publish of this loopback. See example in the Akka framework philosophy :
https://github.com/vortex314/akkaEsp32/blob/master/main/MqttSerial.cpp
So far this showed me that I can disconnect/connect several times and everything keeps going. Also starting and stopping serial2mqtt recovers.

Just a point of attention : if the serial device is kept open a Raspberry Linux side during a physical disconnect/connect phase there is a risk that your Arduino gets a renumbered serial device , example : going from /dev/ttyUSB0 to /dev/ttyUSB1. 

I'll try to make an Arduino based example that should apply this approach. 

Hope this helps,
Lieven

PS : keep on providing feedback. :-)
